# Generated by Django 5.1.7 on 2025-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imy', models.CharField(max_length=50, verbose_name='Название фильма')),
                ('opisanie', models.CharField(max_length=200, verbose_name='Краткое описание фильма')),
                ('otziv', models.TextField(verbose_name='Отзыв')),
            ],
        ),
    ]
